### ISSUE TITLE
SymmetricMatrix::GetEigen memory corruption

### ISSUE THREAD

**Issue by chpatrick** [microsoft/UVAtlas#59] opened 2021-03-04 00:43 UTC
I found some memory corruption in the SymmetricMatrix::GetEigen function. I think it's caused by the following line: https://github.com/microsoft/UVAtlas/blob/0437b92e3d33eb6391aaf4cacbd1e8f25eaa6253/UVAtlas/isochart/SymmetricMatrix.hpp#L222

In this for loop `i` goes up to `i < dwDimension - 1`, but `pEigenValue` is of size `dwMaxRange`, and `dwMaxRange <= dwDimension`.

I have a version that replaces that function with a call to the Eigen library here: https://github.com/chpatrick/UVAtlas/commit/d009630b995a79d072a6402e3e394ed2c96c5bdf

**Comment by nh2** [comment] 2021-03-04 00:54
> I have a version that replaces that function with a call to the Eigen library here: [chpatrick@d009630](https://github.com/chpatrick/UVAtlas/commit/d009630b995a79d072a6402e3e394ed2c96c5bdf)

This also replaces the **O(n^3)** sorting (!) algorithm used so far to emit eivenvalues/vector in descending order.

https://github.com/microsoft/UVAtlas/blob/0437b92e3d33eb6391aaf4cacbd1e8f25eaa6253/UVAtlas/isochart/SymmetricMatrix.hpp#L436-L451

So far if you called `GetEigen()` on a 14k-square matrix, just the sorting of the results of at the end would require `14000^3 = 2744000000000 = ~3 Tera-swaps`.

**Comment by nh2** [comment] 2021-03-05 11:16
> This also replaces the **O(n^3)** sorting (!) algorithm

Embarassingly, I am wrong; **Eigen also uses a O(n^3) sort**:

https://gitlab.com/libeigen/eigen/-/blob/6cbb3038ac48cb5fe17eba4dfbf26e3e798041f1/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h#L535-551

**Comment by walbourn** [comment] 2021-05-30 06:36
The test at the start of ``GetEigen`` establishes that ``dwMaxRange >= dwDimension``, but you wrote ``<=``.

```
            if (dwDimension < dwMaxRange
                || dwMaxRange == 0
                || dwDimension == 0)
            {
                return false;
            }
```

**Comment by chpatrick** [comment] 2021-05-30 13:13
No, that check establishes that `dwMaxRange <= dwDimension`, otherwise it returns false.

The opposite wouldn't make any sense because the goal of this function is to compute only `dwMaxRange` eigenvalues out of a maximum of `dwDimension`.

**Comment by walbourn** [comment] 2021-05-30 22:23
OK, I"ll take another look. I'll also integrate the opt-in use of the Eigen library to my CMakeList.txt, probably through a build option. For my vcpkg port, I should be able to make use of the [eigen3](https://github.com/microsoft/vcpkg/tree/master/ports/eigen3) port for the dependency.

**Comment by walbourn** [comment] 2021-05-31 20:20
OK, I think the problem is that the algorithm in that header is trying to use ``pEigenValues`` as the temporary space as well as the final answer, which is obviously going to fail in some conditions.

**Comment by walbourn** [comment] 2021-05-31 20:49
Fixed in [this commit](https://github.com/microsoft/UVAtlas/commit/4a287a8bf3efd7cbfa705271bd672cc4155245a7)

**Comment by walbourn** [comment] 2021-05-31 23:48
Added an opt-in build-option to CMake to support using the Eigen library. See [this commit](https://github.com/microsoft/UVAtlas/commit/414e236f270a28fafac8ae3bd9a1f7375cbd2d7c)

**Closed by walbourn** 2021-05-31 23:48 UTC
Labels: bug
